### ISSUE TITLE
Milestones to first useable version

### ISSUE THREAD

**Issue by dpo** [rjbaraldi/ShiftedProximalOperators#1]
- [x] add a `compat` section in `Project.toml`: https://pkgdocs.julialang.org/v1/toml-files
- [x] `ShiftedProximalFunction` should be `ShiftedProximableFunction`
- [x] is `PROXPATH` necessary?
- [x] field `s` is missing from `ShiftedNormL0`
- [x] I can try to deal with the “R undefined” issue
- [x] fix indentation? I find 8 spaces too much. Normal is 4. I use 2
- [x] `(ψ::ShiftedProximalFunction)(y) = ψ.h(ψ.x + y)` is defined twice; define it once in ShiftedProximalOperators.jl
- [x] `prox(ψ::ShiftedNormL0BInf,  q, σ)` allocates
- [x] unit tests
